baseURL = 'https://ting-2023.github.io/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme = 'anatole'

#此代码仅调整侧边栏中的页面标题
[params]
title = "Ting的博客"
author = "Ting"
description = "一些进步，一些思考"
profilePicture = "/images/雪景2.jpg"
#时间格式设置
listDateFormat = "2006-01-02  Monday"
singleDateFormat = "2006-01-02  Monday"
indexDateFormat = "2006-01-02  Monday"
